# Generated by Django 5.2.4 on 2025-07-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_invoice_date_invoiceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_account_name', models.CharField(max_length=255)),
                ('iban', models.CharField(max_length=50)),
                ('swift_code', models.CharField(max_length=50)),
            ],
        ),
    ]
